apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-nombreDelProyecto-hpa
  namespace: aplicaciones
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-nombreDelProyecto
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 95

          