apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-nombreDelProyecto
  namespace: bd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi