apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-nombreDelProyecto
  namespace: bd
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nombreDelProyecto"